### PR TITLE
Add support for unicode characters

### PR DESCRIPTION
**Pull request by TheDeathStreaker**
Since I need this plugin for a project i am working on and I use som of unicode characters i propose this to be added to plugin

### CODE REVIEW

**Comment by sindresorhus** [comment]
I would rather target Node.js 6 and use the `u` regex flag. Would you be willing to make the change?

**Comment by TheDeathStreaker** [comment]
Well this was tested with node 5.12.0 since the project this is being used in is currently unable to be updated to node 6+. But I can make the change and test

**Comment by sindresorhus** [comment]
Ah, I was thinking we could use property escapes, but turns out it's still just a proposal: http://2ality.com/2017/07/regexp-unicode-property-escapes.html

**Comment by TheDeathStreaker** [comment]
Ye I made also was looking if it works like that. It doesn't. Currently xRegExp library takes care of that

**Comment by joscha** [comment]
references #12

**Comment by styfle** [comment]
> I was thinking we could use property escapes, but turns out it's still just a proposal

So now that this proposal is [Stage 4](https://tc39.github.io/proposal-regexp-unicode-property-escapes/), the `xregexp` dependency could be removed in a year or so?

I'm trying to find which version of node this landed in 😅

**Pull request merged**
